services:
  - type: web
    name: bff-spring-boot
    plan: free
    runtime: docker
    repo: https://github.com/TCasablancas/my-boxy-backend-dev
    branch: main
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.uzgpndjyjfmwzteygbjb.supabase.co:5432/postgres
      - key: SUPABASE_DB_USERNAME
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_JWT_ISSUER_URI
        sync: false
      - key: PGCRYPTO_SECRET_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
