services:
  - type: web
    name: bff-spring-boot
    plan: free
    runtime: docker
    repo: https://github.com/TCasablancas/my-boxy-backend-dev
    branch: main
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.uzgpndjyjfmwzteygbjb.supabase.co:6543/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
